package org.dice_research.cel.tree;

import java.util.Objects;

import javolution.util.FastBitSet;

/**
 * Represents a node in the binary decision tree.
 * 
 * Based on code generated by Devstral.
 * 
 * @author Michael R&ouml;der (michael.roeder@uni-paderborn.de)
 *
 */
public class DecisionTreeNode extends SimpleFeatureProfile {

    // The feature used at this node to make decisions.
    private Feature feature;

    // True child of this node (left branch).
    private DecisionTreeNode trueChild;

    // False child of this node (right branch).
    private DecisionTreeNode falseChild;

    // Is this a leaf node? (classification result)
    private boolean isLeaf;

    // Class label for leaf nodes ('positive' or 'negative').
    private boolean isPositiveClass = false;

    public DecisionTreeNode(Feature feature, FastBitSet positives, FastBitSet negatives) {
        super(positives, negatives);
        this.feature = feature;
        this.isLeaf = false;
    }

    public DecisionTreeNode(boolean isPositiveClass, FastBitSet positives, FastBitSet negatives) {
        super(positives, negatives);
        this.isPositiveClass = isPositiveClass;
        this.isLeaf = true;
    }

    // Setters and getters
    public Feature getFeature() {
        return feature;
    }

    public void setTrueChild(DecisionTreeNode trueChild) {
        this.trueChild = trueChild;
    }

    public void setFalseChild(DecisionTreeNode falseChild) {
        this.falseChild = falseChild;
    }

    public boolean isLeaf() {
        return isLeaf;
    }

    public String getClassLabel() {
        return isPositiveClass ? "positive" : "negative";
    }

    public boolean isPositiveClass() {
        return isPositiveClass;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        DecisionTreeNode that = (DecisionTreeNode) o;
        return isLeaf == that.isLeaf && Objects.equals(feature, that.feature)
                && Objects.equals(positives, that.positives) && Objects.equals(negatives, that.negatives)
                && Objects.equals(trueChild, that.trueChild) && Objects.equals(falseChild, that.falseChild)
                && Objects.equals(isPositiveClass, that.isPositiveClass);
    }

    @Override
    public int hashCode() {
        return Objects.hash(feature, positives, negatives, trueChild, falseChild, isLeaf, isPositiveClass);
    }

    public DecisionTreeNode getTrueChild() {
        return trueChild;
    }

    public DecisionTreeNode getFalseChild() {
        return falseChild;
    }

    public FastBitSet getPositives() {
        return positives;
    }

    public FastBitSet getNegatives() {
        return negatives;
    }
}