package org.dice_research.cel.tree;

import java.util.Collection;

import org.dice_research.cel.data.LearningProblemSatistics;
import org.dice_research.cel.tree.select.FeatureSelector;

import javolution.util.FastBitSet;

/**
 * A simple decision tree learner.
 * 
 * Based on code generated by Devstral.
 * 
 * @author Michael R&ouml;der (michael.roeder@uni-paderborn.de)
 *
 */
public class DecisionTreeLearner<T extends Feature> {

    protected static boolean USE_GINI_INDEX = true;

    protected FeatureSelector<T> selector;

    public DecisionTreeLearner(FeatureSelector<T> selector) {
        super();
        this.selector = selector;
    }

    // Method to train a decision tree.
    public DecisionTreeNode learn(Collection<T> features, LearningProblemSatistics lpStats) {
        FastBitSet positives = FastBitSet.newInstance();
        positives.set(0, lpStats.numberOfPositives);
        FastBitSet negatives = FastBitSet.newInstance();
        negatives.set(0, lpStats.numberOfNegatives);
        return buildTree(features, positives, negatives, lpStats);
    }

    protected DecisionTreeNode buildTree(Collection<T> features, FastBitSet positives, FastBitSet negatives,
            LearningProblemSatistics lpStats) {
        // If all examples have the same label, create a leaf node.
        if (positives.cardinality() == 0) {
            return new DecisionTreeNode(false, positives, negatives);
        }
        if (negatives.cardinality() == 0) {
            return new DecisionTreeNode(true, positives, negatives);
        }

        // Select the best feature to split on
        Feature bestFeature = selector.selectBestFeature(features, positives, negatives, lpStats);
        if (bestFeature == null) {
            return new DecisionTreeNode(positives.cardinality() >= negatives.cardinality(), positives, negatives);
        }

        // Create the root node with the selected feature and threshold
        DecisionTreeNode root = new DecisionTreeNode(bestFeature, positives, negatives);

        // Split data based on the chosen feature and recurse for each subset.
        FastBitSet newPositives = createBitSetForChild(positives, lpStats.numberOfPositives, bestFeature.getSelectedPositives(),
                false);
        FastBitSet newNegatives = createBitSetForChild(negatives, lpStats.numberOfNegatives, bestFeature.getSelectedNegatives(),
                false);

        root.setTrueChild(buildTree(features, newPositives, newNegatives, lpStats));

        newPositives = createBitSetForChild(positives, lpStats.numberOfPositives, bestFeature.getSelectedPositives(), true);
        newNegatives = createBitSetForChild(negatives, lpStats.numberOfNegatives, bestFeature.getSelectedNegatives(), true);

        root.setFalseChild(buildTree(features, newPositives, newNegatives, lpStats));

        return root;
    }

    protected static FastBitSet createBitSetForChild(FastBitSet instances, int instanceCount,
            FastBitSet featureSelection, boolean falseChild) {
        FastBitSet newSet = FastBitSet.newInstance();
        newSet.or(featureSelection);
        if (falseChild) {
            newSet.flip(0, instanceCount);
        }
        newSet.and(instances);
        return newSet;
    }

}